import type { Metadata } from "next";
import { Inter, Satisfy } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import BlindContextProvider from "@/utils/BlindContext";

const satisfy = Satisfy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-satisfy",
});
const satoshi = localfont({
  src: "./fonts/Satoshi-Variable.ttf",
  display: "swap",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Mayou: Lost in the Sauce",
  description: "Generated by create next app",
};

// Satoshi: ["400", "500", "700", "900"]

// todo: add custom favicon

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${satisfy.variable} bg-base font-sans text-clr-prmry`}
      >
        <BlindContextProvider>{children}</BlindContextProvider>
      </body>
    </html>
  );
}
